[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
    "openai>=1.78.1",
    "psutil>=7.0.0",
    "pydantic>=2.11.4",
    "pydantic-settings>=2.9.1",
    "sentence-transformers>=4.1.0",
    "uvicorn>=0.34.2",
]
